# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_key_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='domain',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
